#!/bin/bash

#A script which blacklists an IP or unblocks an IP
#Parameters:
#
#-i <string>
#-a <list|delist>
#-d <number>

basename=`basename $0`
NO_ARGS=0
DIR="/var/log/blacklist"
BLOCKED_LOG="$DIR/block.log"
UNBLOCKED_LOG="$DIR/unblocked.log"
PROBLEM_LOG="$DIR/problem.log"

if [ -f /usr/share/blacklist/lang/ru ]
then
	. /usr/share/blacklist/lang/ru
fi

if [ -f /usr/bin/blacklist-libs ]
then
	. /usr/bin/blacklist-libs
fi

if [ $# = $NO_ARGS ]
then
    usage
fi

while getopts "i:a:dcf:vh" arg; do
    case $arg in
	i)	IP=${OPTARG}
		;;

	a)	ACTION=${OPTARG}
		;;

	d)	IPVERSION=${OPTARG}
	    if [[ $IPVERSION != 4 && $IPVERSION != 6 ]]
	    then
		    usage
	    fi
	    ;;
	    
	c)	count
	    exit 0
	    ;;
	f)  file_operation=1
	    block_from_file ${OPTARG}
	    exit 0
	    ;;
    
	v)	echo "IP blocking script; version 0.2"
	    exit 0
	    ;;
	    
	h)	help
	    ;;
	    
	*)	usage
	    ;;
    esac
done


if [[ $ACTION != "list" && $ACTION != "delist" ]]
then
	usage
fi

if [[ -z $IPVERSION ]]
then
    IP_VERSION=4
else
    IP_VERSION=$IPVERSION
fi

case $ACTION in
    list)
	if [[ $IP_VERSION = 4 ]]
	then
	    block_ip_v4 $IP
	    exit 0
	else
	    block_ip_v6 $IP
	    exit 0
	fi
	exit 0
	;;
	
    delist)	if [[ $IP_VERSION = 4 ]]
	then
	    unblock_ip_v4 $IP
	else
	    unblock_ip_v6 $IP
	fi
	exit 0
	;;
	
    count)	count
	;;
	
    block)	block="1"
	;;
    
    unblock)	block="0"
	;;
	
    *)	usage
	exit 1
esac